[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
sqlx = { version = "0.7.1", features = [
    "chrono",
    "postgres",
    "runtime-tokio-native-tls",
] }
tokio = { version = "1.39.2", features = ["macros", "rt-multi-thread"] }
validator = { version = "0.18.1", features = ["derive"] }
once_cell = "1.19.0"
regex = "1.10.5"
anyhow = "1.0.86"
testcontainers = "0.21.0"
lazy_static = "1.5.0"
ctor = "0.2.8"
serde = { version = "1.0.204", features = ["derive"], optional = true }

[features]
default = []
serde = ["dep:serde"]
