[workspace]
members = ["engine", "bin-shuttle"]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3

[profile.test]
opt-level = 0 # No optimization for tests
debug = true  # Include debug information
