name: Shuttle Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update stable
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
        working-directory: "server"
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
          working-directory: "server"
          name: "a-few-words"
          no-test: true
          secrets: |
            google_translate_api_key = '${{ secrets.GOOGLE_TRANSLATE_API_KEY }}'
            cognito_user_pool_id = '${{ secrets.COGNITO_USER_POOL_ID }}'
            cognito_client_id = '${{ secrets.COGNITO_CLIENT_ID }}'
            cognito_region = '${{ secrets.COGNITO_REGION }}'
